### ISSUE TITLE
Badger support

### ISSUE THREAD

**Issue by jackmcgary** [timshannon/bolthold#41]
Love this. Any plans for badger support? Anything you know of that would make it difficult to port? Thx.

**Comment by timshannon** [comment]
Yeah, I'd definitely love to add badger support.  I've been debating whether or not to make it a separate library.

I think I'll see if I can integrate it without too much having to change.

**Comment by nkev** [comment]
+1 "Badgerhold" would go off, me thinks.

**Comment by ivanjaros** [comment]
+1 for badger. Bolt has blocking transactions(so you have to do batches to get sane performance) whereas badger does not. My latest testing was 250 bolt transactions vs 15 000 badger transactions per second.

**Comment by timshannon** [comment]
Alright I've opened up a new repository where I'll start on BadgerHold:

https://github.com/timshannon/BadgerHold

Follow the repo there for updates.

**Comment by timshannon** [comment]
I'm closing this issue, as [BadgerHold](https://github.com/timshannon/badgerhold) looks ready for use currently.  The master branch passes all tests, although there is [one outstanding issue](https://github.com/timshannon/badgerhold/issues/1) that I'm still working through, and hope to get resolved shortly.

I've also written up a comparison between BoltDB and Badger since I've had the opportunity to implement the exact same library on both databases.  

https://tech.townsourced.com/post/boltdb-vs-badger/

**Comment by nkev** [comment]
@timshannon Great article. I'm surprised about Badgers high memory consumption. My plan was to use multiple badger instances (one for each customer), but now I think I'll go back to BoltDB.

**Comment by timshannon** [comment]
You should read the exchange here: https://github.com/dgraph-io/badger/pull/704#issuecomment-459080457

The Dgraph guys themselves, don't seem to have any issues running multiple instances, so you might want to do your own testing to confirm for yourself.
