### ISSUE TITLE
move away query/criterion so we can re use it against a regular sql db ?

### ISSUE THREAD

**Issue by mh-cbon** [timshannon/bolthold#61]
do you have any thoughts about that ? I see you already done badger and boltdb, they are similar (?) yet they use a different base source code.

I m interested into using a regular sql db in the way i do with bolt.
in my opinion the current query api is definitely capable of doing this.

I still see some advantages in using slq db, its definitely more matured, yet i really like the way i work with bolt.

Do you have any thoughts or ideas to share about this ?

**Comment by timshannon** [comment]
The query api for bolthold is very limited.  You'd be handicapping yourself by using it with an SQL database.  SQL is much more expressive and standardized.  I don't see the value gained by doing this?

The whole point of creating BoltDB was to put a simple querying interface on top of  Bolt because one didn't already exist.

If you really want a non-sql interface on top of an SQL database, you should check out [GORM](https://gorm.io/)

**Comment by mh-cbon** [comment]
I do see value, i could move from/to a variety of database engine in a glance.

I could use bolt as an efficient internal memory storage for small deployment, where as for larger deployments i can make use of a more mature engine to handle some edge cases more appropriately.

backup, replication, read/write master slave, indexing, search etc are more mature using those engine. Anyways, i could aswell go for mongodb or CockroachDB, for sure, but again, i see no reason why the query api could not be used for those.
