### ISSUE TITLE
Weird key prefixes (problem with boltdbweb)

### ISSUE THREAD

**Issue by n1try** [timshannon/bolthold#84]
Probably this is not within the competence of this project, but I'm trying to understand the following problem. I tried to access buckets, that were created through bolthold, using [evnix/boltdbweb](https://github.com/evnix/boltdbweb). When trying to delete a certain key it wouldn't work. After some debugging, I found that a key, e.g. `me@example.com` is actually prefixed by a few non-printable characters in boltdbweb and is therefore not found. 
Probably the problem is on boltdbweb's side, but I'd be happy if anyone has a moment to take a look at that. Otherwise, just close this issue again, please.

**Comment by timshannon** [comment]
Are you looking at the `_index` bucket or the main bucket.  And modification outside of bolthold of a bolt database will cause issues with the indexes.

Also, when you use Bolthold, by default it marshals all the data into [Gobs](https://golang.org/pkg/encoding/gob/), including key values, so that's probably why you see extra characters in front of the key values.  The gob format adds some binary type info into the byte array.

My guess is that boltdbweb tries to convert everything to string for display, and possibly uses that same string for running deletes?  If that's the case, then there definitely is some data lost in the conversion.

Key Type -> Gob Byte Array -> String -> Byte Array

I'm guessing an issue needs to be opened with boltdbweb.

**Comment by n1try** [comment]
>  And modification outside of bolthold of a bolt database will cause issues with the indexes

Yes, I know. Only wanted to have the web interface to quickly inspect the data. 

> all the data into Gobs, including key values

Alright, so that's the reason. Makes sense! I assumed keys were stored as plain strings. 

> My guess is that boltdbweb tries to convert everything to string for display, and possibly uses that same string for running deletes?

The key is submitted as a URL query parameter in boltdbweb, so yes, non-Unicode binary data will definitely be lost.

I thought of using JSON for encoding instead of gob, although that's less efficient. We'll see. Anyway, thanks a lot for your reply, it helped me understand the issue.

Are there plans to have something like a minimalist web GUI for bolthold some time in there future? 😃

**Comment by timshannon** [comment]
No plans currently.
